export enum ReclamationType {
  COURSE_CONTENT_ISSUES = 'COURSE_CONTENT_ISSUES',
  TECHNICAL_PROBLEMS = 'TECHNICAL_PROBLEMS',
  INSTRUCTOR_OR_SUPPORT_CLAIM = 'INSTRUCTOR_OR_SUPPORT_CLAIM',
  GRADING_AND_ASSESSMENT_DISPUTES = 'GRADING_AND_ASSESSMENT_DISPUTES',
  ACCOUNT_AND_PAYMENT_ISSUES = 'ACCOUNT_AND_PAYMENT_ISSUES',
  OTHER = 'OTHER'
}
